port: 8765
bind: 127.0.0.1
# Allow only simple, low-risk commands initially. Expand later under policy.
allowlist:
  - "python --version"
  - "python -V"
  - "pip --version"
  - "echo hello"
time_limits:
  run_seconds: 30
log_file: "logs/leb_service.log"
