# tools/py/agentic/sample_proposal.py

# allow running as a script or as a module
if __package__ in (None, ""):
    import os, sys
    _here = os.path.dirname(__file__)
    _pkg_root = os.path.dirname(_here)              # tools/py
    if _pkg_root not in sys.path:
        sys.path.insert(0, _pkg_root)
    __package__ = "agentic"


import os, sys, json, time
from .patch_utils import sha256_hex, ensure_dir

ROOT = os.path.abspath(os.getcwd())
OUT_DIR = os.path.join(ROOT, "tmp", "patches")

def pick_target():
    cands = [
        os.path.join(ROOT, "docs", "USER_GUIDE.md"),
        os.path.join(ROOT, "README.md"),
        os.path.join(ROOT, "project", "plans", "project_plan_v3.yaml"),
    ]
    for p in cands:
        if os.path.isfile(p):
            return p
    raise FileNotFoundError("No target file found among docs/USER_GUIDE.md, README.md, project/plans/project_plan_v3.yaml")

def main():
    target = pick_target()
    rel = os.path.relpath(target, ROOT).replace("\\", "/")
    expected = sha256_hex(target)
    proposal = {
        "feature_id": "DEV-DRY-RUN",
        "description": "Harmless marker append for dry-run pipeline test",
        "dry_run": True,
        "changes": [
            {
                "path": rel,
                "mode": "append",
                "expected_sha256": expected,
                "content": "\n<!-- sample patch ok: {ts} -->\n".format(ts=int(time.time()))
            }
        ],
        "meta": {
            "created_utc": int(time.time()),
            "author": "PA",
            "notes": "generated by sample_proposal.py"
        }
    }
    ensure_dir(OUT_DIR)
    out = os.path.join(OUT_DIR, f"proposal_{int(time.time())}.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(proposal, f, indent=2)
    print(out)

if __name__ == "__main__":
    sys.exit(main())
