import argparse, subprocess, sys, datetime, base64
from pathlib import Path

FILES = {
    'tools/ps1/register_pack_fetcher.ps1': b'cGFyYW0oW3N0cmluZ10kVGFza05hbWUgPSAnUEFfUGFja0ZldGNoZXInLCBbaW50XSRFdmVyeU1pbnV0ZXMgPSAxKQokRXJyb3JBY3Rpb25QcmVmZXJlbmNlPSdTdG9wJwoKZnVuY3Rpb24gUXVvdGUoW3N0cmluZ10kcykgewogIGlmICgkcyAtbWF0Y2ggJ1xzJykgeyByZXR1cm4gJyInICsgJHMgKyAnIicgfSBlbHNlIHsgcmV0dXJuICRzIH0KfQoKZnVuY3Rpb24gUHdzaFBhdGggewogICRjYW5kaWRhdGVzID0gQCgKICAgICIkZW52OlByb2dyYW1GaWxlc1xQb3dlclNoZWxsXDdccHdzaC5leGUiLAogICAgIiRlbnY6UHJvZ3JhbUZpbGVzXFBvd2VyU2hlbGxcNy1wcmV2aWV3XHB3c2guZXhlIiwKICAgICIkZW52OlN5c3RlbVJvb3RcU3lzdGVtMzJcV2luZG93c1Bvd2VyU2hlbGxcdjEuMFxwb3dlcnNoZWxsLmV4ZSIKICApCiAgZm9yZWFjaCAoJHAgaW4gJGNhbmRpZGF0ZXMpIHsgaWYgKFRlc3QtUGF0aCAkcCkgeyByZXR1cm4gJHAgfSB9CiAgcmV0dXJuICJwb3dlcnNoZWxsLmV4ZSIKfQoKIyByZXBvIHJvb3QgPSBwYXJlbnQgb2YgdGhpcyBzY3JpcHQgZm9sZGVyCiRyb290ID0gKFJlc29sdmUtUGF0aCAoU3BsaXQtUGF0aCAtUGFyZW50ICRNeUludm9jYXRpb24uTXlDb21tYW5kLlBhdGgpKS5QYXRoCiRzY3JpcHQgPSBKb2luLVBhdGggJHJvb3QgJ3J1bl9wYWNrX2ZldGNoZXIucHMxJwokcHdzaCA9IChQd3NoUGF0aCkKCiR0ciA9IChRdW90ZSgkcHdzaCkgKyAnIC1Ob1Byb2ZpbGUgLUV4ZWN1dGlvblBvbGljeSBCeXBhc3MgLUZpbGUgJyArIFF1b3RlKCRzY3JpcHQpKQoKJGFyZ3MgPSBAKAogICcvQ1JFQVRFJywKICAnL1NDJywnTUlOVVRFJywnL01PJywiJEV2ZXJ5TWludXRlcyIsCiAgJy9UTicsIiRUYXNrTmFtZSIsCiAgJy9UUicsIiR0ciIsCiAgJy9STCcsJ0hJR0hFU1QnLAogICcvRicKKQoKIyBVc2UgU3RhcnQtUHJvY2VzcyBmb3IgcmVsaWFibGUgcXVvdGluZwokcHNpID0gTmV3LU9iamVjdCBTeXN0ZW0uRGlhZ25vc3RpY3MuUHJvY2Vzc1N0YXJ0SW5mbwokcHNpLkZpbGVOYW1lID0gJ1NDSFRBU0tTJwokcHNpLkFyZ3VtZW50cyA9ICgkYXJncyAtam9pbiAnICcpCiRwc2kuVXNlU2hlbGxFeGVjdXRlID0gJGZhbHNlCiRwc2kuUmVkaXJlY3RTdGFuZGFyZE91dHB1dCA9ICR0cnVlCiRwc2kuUmVkaXJlY3RTdGFuZGFyZEVycm9yICA9ICR0cnVlCgokcCA9IE5ldy1PYmplY3QgU3lzdGVtLkRpYWdub3N0aWNzLlByb2Nlc3MKJHAuU3RhcnRJbmZvID0gJHBzaQokbnVsbCA9ICRwLlN0YXJ0KCkKJHN0ZG91dCA9ICRwLlN0YW5kYXJkT3V0cHV0LlJlYWRUb0VuZCgpCiRzdGRlcnIgPSAkcC5TdGFuZGFyZEVycm9yLlJlYWRUb0VuZCgpCiRwLldhaXRGb3JFeGl0KCkKCmlmICgkcC5FeGl0Q29kZSAtbmUgMCkgewogIFdyaXRlLUVycm9yICJzY2h0YXNrcyBmYWlsZWQgKCQoJHAuRXhpdENvZGUpKS4gU3Rkb3V0OmBuJHN0ZG91dGBuU3RkZXJyOmBuJHN0ZGVycmBuVHJ5IHJ1bm5pbmcgYXMgQWRtaW5pc3RyYXRvciBvciB1c2UgVGFzayBTY2hlZHVsZXIgVUkuIgp9IGVsc2UgewogIFdyaXRlLUhvc3QgJHN0ZG91dC5UcmltRW5kKCkKICBXcml0ZS1Ib3N0ICJTY2hlZHVsZWQgdGFzayAnJFRhc2tOYW1lJyBjcmVhdGVkIHRvIHJ1biBldmVyeSAkRXZlcnlNaW51dGVzIG1pbnV0ZShzKS4iCn0=',
    'docs/phone_workflow.md': b'IyBQaG9uZS1maXJzdCBBcHByb3ZhbCBXb3JrZmxvdyAoUmVjb21tZW5kZWQpCgojIyBPcHRpb24gQSDigJQgU3RhYmxlIFRhZyAobm8gSlNPTiwgZWFzaWVzdCkKMS4gT24gaVBob25lIChTYWZhcmkpOiBSZXBvIOKGkiBSZWxlYXNlcyDihpIgY3JlYXRlIChvbmNlKSBvciBvcGVuIHRhZyAqKlBBLU9VVFBVVCoqLgoyLiBFZGl0IHJlbGVhc2Ug4oaSIHJlbW92ZSBvbGQgYXNzZXRzIOKGkiB1cGxvYWQgbmV3IGBQQV9PVVRQVVRfPGFueXRoaW5nPi56aXBgIOKGkiBVcGRhdGUuCjMuIFBDIGZldGNoZXIgKHNjaGVkdWxlZCkgd2lsbCBkZXRlY3QgYW5kIGFwcGx5IGF1dG9tYXRpY2FsbHkuCgojIyBPcHRpb24gQiDigJQgQ29udHJvbCBGaWxlICsgVVJMIChncmVhdCB3aXRoIENoYXRHUFQgbGlua3MpCjEuIE9uIGlQaG9uZSAoR2l0SHViIE1vYmlsZSk6IEFkZCBmaWxlIGBjb250cm9sL25leHRfcGFjay5qc29uYCBhdCByZXBvIHJvb3Q6CiAgIGBgYGpzb24KICAgeyJzb3VyY2UiOiJ1cmwiLCJ1cmwiOiI8ZGlyZWN0IHBhY2sgVVJMPiIsIm5hbWUiOiJQQV9PVVRQVVRfPGFueXRoaW5nPi56aXAifQogICBgYGAKMi4gQ29tbWl0IHRvIGBtYWluYC4gVGhlIFBDIGZldGNoZXIgd2lsbCBkb3dubG9hZCB0aGUgVVJMIGFuZCBhcHBseS4KCiMjIEdldHRpbmcgU3RhdHVzIG9uIFlvdXIgUGhvbmUKLSBRdWljazogY2hlY2sgYHJlcG9ydHMvb3BzL3BhY2tfZmV0Y2hlci5sb2dgIGFuZCBgcmVwb3J0cy9vcHMvaGVsbG9fcGFja19hcHBsaWVkLnR4dGAgaW4gdGhlIHJlcG8uCi0gTmV4dCBzdGVwICh0byBiZSBhZGRlZCk6IFBDIHdpbGwgcHVibGlzaCBgcmVwb3J0cy9vcHMvc3RhdHVzLm1kYCBhbmQgYGRvY3Mvb3BzL2luZGV4Lmh0bWxgIChHaXRIdWIgUGFnZXMpIGFmdGVyIGVhY2ggcnVuIGZvciBhIGNsZWFuIHBob25lIHZpZXcu',
}

def run(a, cwd=None, check=True): subprocess.run(a, cwd=cwd, check=check)

def find_root(seed: Path) -> Path:
    p = seed
    for _ in range(8):
        if (p/'.git').exists(): return p
        p = p.parent
    return seed

def main():
    here = Path(__file__).resolve()
    root = find_root(here)

    for rel, b64 in FILES.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(base64.b64decode(b64))

    step='PA-313'; branch=f'step/{step}-fix-register'
    ts=datetime.datetime.now().strftime('%Y%m%d_%H%M')
    run(['git','checkout','-B',branch], root)
    run(['git','add','-A'], root)
    run(['git','commit','-m', f'{step}: fix register_pack_fetcher.ps1; add phone workflow doc'], root, check=False)
    run(['git','push','-u','origin',branch], root, check=False)
    print(f'{step} done.')

if __name__ == '__main__': sys.exit(main())