
import subprocess, sys, base64
from pathlib import Path
FILES={'tools/py/web_mobile_inventory.py':b'CmltcG9ydCBqc29uLCBhc3QsIHJlLCBzeXMKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoClRBR19MSUJTPXsnZmxhc2snLCdmYXN0YXBpJywnc3RhcmxldHRlJywnYWlvaHR0cCcsJ3F1YXJ0JywndG9ybmFkbycsJ3V2aWNvcm4nLCdodHRwLnNlcnZlcid9CmRlZiBzY2FuX3B5KHApOgogICAgb3V0PXsnZmlsZSc6c3RyKHApLCdmcmFtZXdvcmtzJzpbXSwncm91dGVzJzpbXSwncG9ydHMnOltdLCdoaW50cyc6W119CiAgICBzPXAucmVhZF90ZXh0KCd1dGYtOCcsZXJyb3JzPSdpZ25vcmUnKQogICAgZm9yIGxpYiBpbiBUQUdfTElCUzoKICAgICAgICBpZiByZS5zZWFyY2gocidcYicrcmUuZXNjYXBlKGxpYikrcidcYicsIHMpOiBvdXRbJ2ZyYW1ld29ya3MnXS5hcHBlbmQobGliKQogICAgZm9yIG0gaW4gcmUuZmluZGl0ZXIocicoPzwhXHcpKFxkezIsNX0pKD8hXHcpJywgcyk6CiAgICAgICAgbj1pbnQobS5ncm91cCgxKSk7IAogICAgICAgIGlmIDgwPD1uPD02NTUzNSBhbmQgbiBub3QgaW4gb3V0Wydwb3J0cyddOiBvdXRbJ3BvcnRzJ10uYXBwZW5kKG4pCiAgICB0cnk6CiAgICAgICAgdD1hc3QucGFyc2UocyxzdHIocCkpCiAgICAgICAgZm9yIG4gaW4gYXN0LndhbGsodCk6CiAgICAgICAgICAgIGlmIGdldGF0dHIobiwnZGVjb3JhdG9yX2xpc3QnLE5vbmUpOgogICAgICAgICAgICAgICAgZm9yIGQgaW4gbi5kZWNvcmF0b3JfbGlzdDoKICAgICAgICAgICAgICAgICAgICBhPWdldGF0dHIoZ2V0YXR0cihkLCdmdW5jJyxOb25lKSwnYXR0cicsTm9uZSkKICAgICAgICAgICAgICAgICAgICBpZiBhIGluIHsnZ2V0JywncG9zdCcsJ3B1dCcsJ3BhdGNoJywnZGVsZXRlJywncm91dGUnfToKICAgICAgICAgICAgICAgICAgICAgICAgb3V0Wydyb3V0ZXMnXS5hcHBlbmQoeydmbic6Z2V0YXR0cihuLCduYW1lJywnJyksICdtZXRob2QnOmEudXBwZXIoKX0pCiAgICBleGNlcHQ6IHBhc3MKICAgIGlmICdodHRwLnNlcnZlcicgaW4gb3V0WydmcmFtZXdvcmtzJ106IG91dFsnaGludHMnXS5hcHBlbmQoJ3N0ZGxpYi1odHRwLXNlcnZlcicpCiAgICByZXR1cm4gb3V0CmRlZiBtYWluKHJvb3QpOgogICAgcj1QYXRoKHJvb3QpLnJlc29sdmUoKQogICAgcHlzPVtdOyBhc3NldHM9W107IHBzMT1bXQogICAgZm9yIHAgaW4gci5yZ2xvYignKicpOgogICAgICAgIGlmIHAuaXNfZGlyKCk6IGNvbnRpbnVlCiAgICAgICAgc2Z4PXAuc3VmZml4Lmxvd2VyKCkKICAgICAgICBpZiBzZng9PScucHknOgogICAgICAgICAgICBpbmZvPXNjYW5fcHkocCkKICAgICAgICAgICAgaWYgaW5mb1snZnJhbWV3b3JrcyddIG9yIGluZm9bJ3JvdXRlcyddIG9yIGluZm9bJ3BvcnRzJ10gb3IgaW5mb1snaGludHMnXTogcHlzLmFwcGVuZChpbmZvKQogICAgICAgIGVsaWYgc2Z4IGluICgnLmh0bWwnLCcuaHRtJywnLmpzJywnLmpzb24nLCcuY3NzJyk6CiAgICAgICAgICAgIGlmIGFueShrIGluIHAucGFydHMgZm9yIGsgaW4gKCd3ZWInLCdkb2NzJywndGVtcGxhdGVzJywnc3RhdGljJywncHVibGljJykpOgogICAgICAgICAgICAgICAgYXNzZXRzLmFwcGVuZChzdHIocCkpCiAgICAgICAgZWxpZiBzZng9PScucHMxJzoKICAgICAgICAgICAgdHh0PXAucmVhZF90ZXh0KCd1dGYtOCcsZXJyb3JzPSdpZ25vcmUnKS5sb3dlcigpCiAgICAgICAgICAgIGlmICdydW5fY29udHJvbF9hcGkucHMxJyBpbiB0eHQgb3IgJ3J1bl9wYWNrX2ZldGNoZXIucHMxJyBpbiB0eHQ6CiAgICAgICAgICAgICAgICBwczEuYXBwZW5kKHN0cihwKSkKICAgIG91dD17J3Jvb3QnOnN0cihyKSwncHknOnB5cywnYXNzZXRzJzphc3NldHMsJ3BzMSc6cHMxfQogICAgZD1yLydyZXBvcnRzJy8nb3BzJzsgZC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAgIChkLyd3ZWJfbW9iaWxlX2ludmVudG9yeS5qc29uJykud3JpdGVfdGV4dChqc29uLmR1bXBzKG91dCxpbmRlbnQ9MiksZW5jb2Rpbmc9J3V0Zi04JykKICAgIChkLyd3ZWJfbW9iaWxlX2ludmVudG9yeS5tZCcpLndyaXRlX3RleHQoJyMgV2ViL01vYmlsZSBJbnZlbnRvcnlcbi0gcHk6IHt9XG4tIGFzc2V0czoge31cbi0gcHMxOiB7fVxuJy5mb3JtYXQobGVuKHB5cyksbGVuKGFzc2V0cyksbGVuKHBzMSkpLGVuY29kaW5nPSd1dGYtOCcpCmlmIF9fbmFtZV9fPT0nX19tYWluX18nOgogICAgbWFpbihzeXMuYXJndlsxXSBpZiBsZW4oc3lzLmFyZ3YpPjEgZWxzZSAnLicpCg==',
        'tools/ps1/run_web_mobile_inventory.ps1':b'CiRFcnJvckFjdGlvblByZWZlcmVuY2U9J1N0b3AnCmZ1bmN0aW9uIEZpbmQtUmVwb1Jvb3QoW3N0cmluZ10kc3RhcnQpIHsKICBpZiAoLW5vdCAkc3RhcnQpIHsgJHN0YXJ0ID0gJFBTU2NyaXB0Um9vdCB9CiAgJGN1ciA9IFJlc29sdmUtUGF0aCAtTGl0ZXJhbFBhdGggJHN0YXJ0CiAgZm9yICgkaT0wOyAkaSAtbHQgMTA7ICRpKyspIHsKICAgIGlmIChUZXN0LVBhdGggKEpvaW4tUGF0aCAkY3VyICcuZ2l0JykpIHsgcmV0dXJuICRjdXIgfQogICAgJHBhcmVudCA9IFNwbGl0LVBhdGggLVBhcmVudCAkY3VyCiAgICBpZiAoJHBhcmVudCAtZXEgJGN1cikgeyBicmVhayB9CiAgICAkY3VyID0gJHBhcmVudAogIH0KICByZXR1cm4gKEdldC1Mb2NhdGlvbikuUGF0aAp9CiRyb290ID0gRmluZC1SZXBvUm9vdCAkbnVsbAomIHB5dGhvbiAoSm9pbi1QYXRoICRyb290ICd0b29sc1xweVx3ZWJfbW9iaWxlX2ludmVudG9yeS5weScpICRyb290CiRjb2RlPSRMQVNURVhJVENPREUKaWYgKCRjb2RlIC1uZSAwKSB7IFdyaXRlLUVycm9yICJpbnZlbnRvcnkgZmFpbGVkICgkY29kZSkiIH0KJG1kID0gSm9pbi1QYXRoICRyb290ICdyZXBvcnRzXG9wc1x3ZWJfbW9iaWxlX2ludmVudG9yeS5tZCcKaWYgKFRlc3QtUGF0aCAkbWQpIHsgR2V0LUNvbnRlbnQgJG1kIC1IZWFkIDQwIH0KZXhpdCAkY29kZQo=',
        'tests/smoke/test_web_mobile_inventory.py':b'CmltcG9ydCBqc29uLCBwYXRobGliCmRlZiB0ZXN0X2ludmVudG9yeV9qc29uX2V4aXN0c19hbmRfdmFsaWQoKToKICAgIHA9cGF0aGxpYi5QYXRoKCdyZXBvcnRzL29wcy93ZWJfbW9iaWxlX2ludmVudG9yeS5qc29uJykKICAgIGFzc2VydCBwLmV4aXN0cygpCiAgICBkYXRhPWpzb24ubG9hZHMocC5yZWFkX3RleHQoJ3V0Zi04JykpCiAgICBhc3NlcnQgJ3B5JyBpbiBkYXRhIGFuZCAnYXNzZXRzJyBpbiBkYXRhIGFuZCAncHMxJyBpbiBkYXRhCg==',
        'docs/ops/roadmap_web_phone.md':b'IyBSb2FkbWFwIHdyaXR0ZW4gaW4gcmVwb3J0cy9vcHMvd2ViX21vYmlsZV9pbnZlbnRvcnkubWQgaGVhZGVyLgo='}
def run(a,cwd=None,check=True): subprocess.run(a,cwd=cwd,check=check)
def find_root(here):
    p=here
    for _ in range(8):
        if (p/'.git').exists(): return p
        p=p.parent
    return here
def main():
    here=Path(__file__).resolve()
    root=find_root(here)
    for rel,b in FILES.items():
        p=root/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_bytes(base64.b64decode(b))
    try: run(['git','checkout','-B','step/PA-340-web-mobile-inventory'],root)
    except Exception: pass
    try: run(['git','add','-A'],root)
    except Exception: pass
    try: run(['git','commit','-m','PA-340: add web/mobile inventory tool + report'],root,check=False)
    except Exception: pass
    try: run(['git','push','-u','origin','step/PA-340-web-mobile-inventory'],root,check=False)
    except Exception: pass
    print('PA-340 done.')
if __name__=='__main__': main()
