import argparse, subprocess, sys, datetime, base64
from pathlib import Path

FILES = {
    'tools/ps1/apply_inbox.ps1': b'cGFyYW0oCiAgW3N0cmluZ10kSW5ib3ggPSAiX2luYm94IiwKICBbc3RyaW5nXSRQcm9jZXNzZWQgPSAiX2luYm94XHByb2Nlc3NlZCIKKQokRXJyb3JBY3Rpb25QcmVmZXJlbmNlPSdTdG9wJwoKZnVuY3Rpb24gRmluZC1SZXBvUm9vdChbc3RyaW5nXSRzdGFydCkgewogIGlmICgtbm90ICRzdGFydCkgeyAkc3RhcnQgPSAoU3BsaXQtUGF0aCAtUGFyZW50ICRNeUludm9jYXRpb24uTXlDb21tYW5kLlBhdGgpIH0KICAkY3VyID0gUmVzb2x2ZS1QYXRoIC1MaXRlcmFsUGF0aCAkc3RhcnQKICBmb3IgKCRpPTA7ICRpIC1sdCAxMDsgJGkrKykgewogICAgaWYgKFRlc3QtUGF0aCAoSm9pbi1QYXRoICRjdXIgJy5naXQnKSkgeyByZXR1cm4gJGN1ciB9CiAgICAkcGFyZW50ID0gU3BsaXQtUGF0aCAtUGFyZW50ICRjdXIKICAgIGlmICgkcGFyZW50IC1lcSAkY3VyKSB7IGJyZWFrIH0KICAgICRjdXIgPSAkcGFyZW50CiAgfQogIHJldHVybiAoR2V0LUxvY2F0aW9uKS5QYXRoCn0KCiRyb290ID0gRmluZC1SZXBvUm9vdCAkUFNTY3JpcHRSb290CiRpbmJveFBhdGggPSBKb2luLVBhdGggJHJvb3QgJEluYm94CiRwcm9jUGF0aCAgPSBKb2luLVBhdGggJHJvb3QgJFByb2Nlc3NlZAoKTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJGluYm94UGF0aCB8IE91dC1OdWxsCk5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICRwcm9jUGF0aCAgfCBPdXQtTnVsbAoKJHppcHMgPSBHZXQtQ2hpbGRJdGVtIC1QYXRoICRpbmJveFBhdGggLUZpbHRlciAqLnppcCAtRmlsZSB8IFNvcnQtT2JqZWN0IExhc3RXcml0ZVRpbWUKaWYgKC1ub3QgJHppcHMpIHsgV3JpdGUtSG9zdCAiYXBwbHlfaW5ib3g6IG5vIHppcHMgaW4gJGluYm94UGF0aCI7IGV4aXQgMCB9Cgpmb3JlYWNoICgkemlwIGluICR6aXBzKSB7CiAgJHN0YW1wID0gR2V0LURhdGUgLUZvcm1hdCAieXl5eU1NZGRfSEhtbXNzIgogICRzdGFnZSA9IEpvaW4tUGF0aCAkcm9vdCAoIl9zdGFnaW5nX3swfSIgLWYgJHN0YW1wKQogIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLUZvcmNlIC1QYXRoICRzdGFnZSB8IE91dC1OdWxsCgogIFdyaXRlLUhvc3QgImFwcGx5X2luYm94OiBleHBhbmRpbmcgJCgkemlwLk5hbWUpIHRvICRzdGFnZSIKICBFeHBhbmQtQXJjaGl2ZSAtTGl0ZXJhbFBhdGggJHppcC5GdWxsTmFtZSAtRGVzdGluYXRpb25QYXRoICRzdGFnZSAtRm9yY2UKCiAgJGFwcGx5ID0gSm9pbi1QYXRoICRzdGFnZSAic2NyaXB0c1xhcHBseV9wYWNrLnBzMSIKICBpZiAoVGVzdC1QYXRoICRhcHBseSkgewogICAgV3JpdGUtSG9zdCAiYXBwbHlfaW5ib3g6IGFwcGx5aW5nICQoJHppcC5OYW1lKSIKICAgICYgcHdzaCAtTm9Qcm9maWxlIC1FeGVjdXRpb25Qb2xpY3kgQnlwYXNzIC1GaWxlICRhcHBseQogICAgJGNvZGUgPSAkTEFTVEVYSVRDT0RFCiAgICBXcml0ZS1Ib3N0ICJhcHBseV9pbmJveDogYXBwbHkgZXhpdCAkY29kZSIKICB9IGVsc2UgewogICAgV3JpdGUtV2FybmluZyAiYXBwbHlfaW5ib3g6IHNjcmlwdHNcYXBwbHlfcGFjay5wczEgbm90IGZvdW5kIGluICQoJHppcC5OYW1lKSIKICAgICRjb2RlID0gMQogIH0KCiAgJGRlc3QgPSBKb2luLVBhdGggJHByb2NQYXRoICR6aXAuTmFtZQogICRpPTEKICB3aGlsZSAoVGVzdC1QYXRoICRkZXN0KSB7CiAgICAkZGVzdCA9IEpvaW4tUGF0aCAkcHJvY1BhdGggKCJ7MH1fezF9ezJ9IiAtZiAkemlwLkJhc2VOYW1lLCRpLCR6aXAuRXh0ZW5zaW9uKTsgJGkrKwogIH0KICBNb3ZlLUl0ZW0gLUxpdGVyYWxQYXRoICR6aXAuRnVsbE5hbWUgLURlc3RpbmF0aW9uICRkZXN0CiAgV3JpdGUtSG9zdCAiYXBwbHlfaW5ib3g6IG1vdmVkICQoJHppcC5OYW1lKSAtPiAkZGVzdCIKCiAgaWYgKCRjb2RlIC1uZSAwKSB7IFdyaXRlLVdhcm5pbmcgImFwcGx5X2luYm94OiBub24temVybyBleGl0ICgkY29kZSkgZm9yICQoJHppcC5OYW1lKSIgfQp9CmV4aXQgMA==',
    'tools/ps1/run_pack_fetcher.ps1': b'cGFyYW0oW3N3aXRjaF0kT25jZSwgW2ludF0kSW50ZXJ2YWxTZWNvbmRzID0gNjAsIFtpbnRdJFRhaWwgPSA4MCkKJEVycm9yQWN0aW9uUHJlZmVyZW5jZT0nU3RvcCcKCmZ1bmN0aW9uIEZpbmQtUmVwb1Jvb3QoW3N0cmluZ10kc3RhcnQpIHsKICAkY3VyID0gUmVzb2x2ZS1QYXRoIC1MaXRlcmFsUGF0aCAoaWYgKCRzdGFydCkgeyAkc3RhcnQgfSBlbHNlIHsgJFBTU2NyaXB0Um9vdCB9KQogIGZvciAoJGk9MDsgJGkgLWx0IDEwOyAkaSsrKSB7CiAgICBpZiAoVGVzdC1QYXRoIChKb2luLVBhdGggJGN1ciAnLmdpdCcpKSB7IHJldHVybiAkY3VyIH0KICAgICRwYXJlbnQgPSBTcGxpdC1QYXRoIC1QYXJlbnQgJGN1cgogICAgaWYgKCRwYXJlbnQgLWVxICRjdXIpIHsgYnJlYWsgfQogICAgJGN1ciA9ICRwYXJlbnQKICB9CiAgcmV0dXJuIChHZXQtTG9jYXRpb24pLlBhdGgKfQoKJHJvb3QgPSBGaW5kLVJlcG9Sb290ICRudWxsCiRweSA9IEpvaW4tUGF0aCAkcm9vdCAndG9vbHNccHlccGFja19mZXRjaGVyLnB5JwppZiAoLW5vdCAoVGVzdC1QYXRoICRweSkpIHsgV3JpdGUtRXJyb3IgInBhY2tfZmV0Y2hlci5weSBub3QgZm91bmQgYXQgJHB5IjsgZXhpdCAyIH0KCldyaXRlLUhvc3QgInJ1bl9wYWNrX2ZldGNoZXI6IHJvb3Q9JHJvb3QiCmlmICgkT25jZSkgewogICYgcHl0aG9uICRweSAtLW9uY2UKfSBlbHNlIHsKICAmIHB5dGhvbiAkcHkgLS1pbnRlcnZhbCAkSW50ZXJ2YWxTZWNvbmRzCn0KJGNvZGUgPSAkTEFTVEVYSVRDT0RFCldyaXRlLUhvc3QgInJ1bl9wYWNrX2ZldGNoZXI6IGV4aXQgJGNvZGUiCgokbG9nID0gSm9pbi1QYXRoICRyb290ICdyZXBvcnRzXG9wc1xwYWNrX2ZldGNoZXIubG9nJwppZiAoVGVzdC1QYXRoICRsb2cpIHsKICBXcml0ZS1Ib3N0ICItLS0tIHRhaWwgcGFja19mZXRjaGVyLmxvZyAobGFzdCAkVGFpbCBsaW5lcykgLS0tLSIKICBHZXQtQ29udGVudCAkbG9nIC1UYWlsICRUYWlsCn0gZWxzZSB7CiAgV3JpdGUtSG9zdCAicGFja19mZXRjaGVyLmxvZyBub3QgZm91bmQgeWV0LiIKfQpleGl0ICRjb2Rl',
}

def run(a, cwd=None, check=True): subprocess.run(a, cwd=cwd, check=check)

def find_root(seed: Path) -> Path:
    p = seed
    for _ in range(8):
        if (p/'.git').exists(): return p
        p = p.parent
    return seed

def main():
    here = Path(__file__).resolve()
    root = find_root(here)

    for rel, b64 in FILES.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(base64.b64decode(b64))

    step='PA-311'; branch=f'step/{step}-fix-apply-inbox'
    ts=datetime.datetime.now().strftime('%Y%m%d_%H%M')
    run(['git','checkout','-B',branch], root)
    run(['git','add','-A'], root)
    run(['git','commit','-m', f'{step}: fix apply_inbox.ps1 and improve run_pack_fetcher diagnostics'], root, check=False)
    run(['git','push','-u','origin',branch], root, check=False)
    print(f'{step} done.')

if __name__ == '__main__':
    sys.exit(main())