name: PA Quality Gate

on:
  push:
  pull_request:

jobs:
  gate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install core tools (yaml/flask/requests)
        run: pip install pyyaml flask requests

      - name: Install repo requirements (optional)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      # Same gate for now to keep checks identical & green.
      - name: Run PA CI gate
        shell: pwsh
        run: python tools/py/ci/ci_check.py
